#!/bin/sh

FAN_DEV=$(for d in /sys/devices/virtual/thermal/cooling_device*; do
    [ -f "$d/type" ] && grep -qE "fan|pwm" "$d/type" && echo $(basename $d) && break
done)
[ -z "$FAN_DEV" ] && exit 0

MAX_VAL=$(cat /sys/devices/virtual/thermal/$FAN_DEV/max_state 2>/dev/null || echo 255)
START_PERCENT=15
START_SPEED=$(( (MAX_VAL * START_PERCENT) / 100 ))
[ "$START_SPEED" -lt 1 ] && [ "$MAX_VAL" -gt 0 ] && START_SPEED=1

uci -q batch <<EOF
set fancontrol.settings.fan_file='/sys/devices/virtual/thermal/$FAN_DEV/cur_state'
set fancontrol.settings.max_speed='$MAX_VAL'
set fancontrol.settings.start_speed='$START_SPEED'
commit fancontrol
EOF
exit 0
